### ISSUE TITLE
Loading new image doesn't clear old grid points

### ISSUE THREAD

**Issue by philpem** [travisgoodspeed/maskromtool#103]
What I did:
- Load an image which has an attached JSON file and a bunch of defined rows and columns
- Load a different image which has no JSON file

What I expected to happen:
The new image loads, with no columns or rows defined.

What actually happened:
The new image loaded, but retained the rows, columns, bits, etc. from the original image.

Workaround:
Completely close and re-open Mask ROM Tool when changing from one image to another.

**Comment by travisgoodspeed** [comment]
The design kept images and `.json` separate, so that you might have one image with multiple bit overlays in a repo.  This has never really been used outside of some test cases, and it's definitely unexpected in the GUI.

The new design clears all objects when replacing the image.  You can still merge objects by loading more than one `.json` file from the CLI, but I don't think that will cause problems.
