### ISSUE TITLE
Tall Sampler

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/maskromtool#39]
Our wide sampler is quite effective on diffusion ROMs that need it.  Close this issue when we have a tall sampler as well.

**Comment by DiscoStarslayer** [comment]
@travisgoodspeed after using your tool to dump a mask rom, I had trouble finding a good clean bit threshold because the bits I was analyzing was not very consistent in the center pixel or the horizontal line. Vertical would be the best.

Left a note to add this functionality and maybe open a PR a few months ago as I did other work as a fully accurate dump was not essential at that time.

Imagine my surprise to see you already did it in the meantime! Amazing work, thank you for all the effort!
