### ISSUE TITLE
Alignment Fails with Gaps Between Rows

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/maskromtool#82]
`RomAlignerNew` gets confused with gaps between rows.  As a temporary workaround, you can rotate your source image by 90 degrees so that the gaps are between columns instead.

**Comment by shirriff** [comment]
Here is my problem case. When I load this into maskromtool, the decoding looks good on the screen. However, when I do View -> ASCII Preview (or any other data dump), the data is completely jumbled and the lines are all different lengths, from 147 to 26 bits.

I assumed that the program simply iterates the rows and the columns to produce the output, so I don't know how it could end up so jumbled. It must be doing something clever :-)

I'll try the workaround.

[test.jpg.json](https://github.com/travisgoodspeed/maskromtool/files/13628879/test.jpg.json)


![test](https://github.com/travisgoodspeed/maskromtool/assets/188116/d690bea2-2f63-4962-a6ae-6ce266d5aa87)

**Comment by shirriff** [comment]
Unfortunately, rotating the image by 90 degrees didn't work. The output is a mixture of long rows of various lengths and one-bit rows. There's no obvious pattern to get the correct data from the dump. It's very frustrating because the tool extracts the data correctly, so I can see it on the screen, but I can't use the data. It's like the tool is taunting me :-)

**Comment by travisgoodspeed** [comment]
Your ninety degree problem should now be fixed by #86.

**Comment by travisgoodspeed** [comment]
Resolved with `RomAlignerReliable` in #88.
